# Generated by Django 5.1.7 on 2025-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='goods_produ_id_844d66_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='goods_produ_id_ed5973_idx'),
        ),
    ]
