# Generated by Django 5.1.7 on 2025-05-12 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +79999999999 или89999999999', regex='^((\\+7)|8)\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
