# Generated by Django 5.1.7 on 2025-05-30 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
